// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tokens.sql

package db_sqlite

import (
	"context"
	"time"
)

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (hash,user_id,expiry,scope) VALUES (?,?,?,?) RETURNING hash, user_id, expiry, scope
`

type CreateTokenParams struct {
	Hash   []byte
	UserID int64
	Expiry time.Time
	Scope  string
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createToken,
		arg.Hash,
		arg.UserID,
		arg.Expiry,
		arg.Scope,
	)
	var i Token
	err := row.Scan(
		&i.Hash,
		&i.UserID,
		&i.Expiry,
		&i.Scope,
	)
	return i, err
}

const deleteAllForUser = `-- name: DeleteAllForUser :exec
DELETE FROM tokens WHERE scope = ? AND user_id = ?
`

type DeleteAllForUserParams struct {
	Scope  string
	UserID int64
}

func (q *Queries) DeleteAllForUser(ctx context.Context, arg DeleteAllForUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteAllForUser, arg.Scope, arg.UserID)
	return err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM tokens WHERE hash = ?
`

func (q *Queries) DeleteToken(ctx context.Context, hash []byte) error {
	_, err := q.db.ExecContext(ctx, deleteToken, hash)
	return err
}

const deleteTokensByUserId = `-- name: DeleteTokensByUserId :exec
DELETE FROM tokens WHERE user_id = ?
`

func (q *Queries) DeleteTokensByUserId(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTokensByUserId, userID)
	return err
}

const getTokensForUser = `-- name: GetTokensForUser :many
SELECT hash, user_id, expiry, scope
FROM tokens
WHERE user_id = ?
`

func (q *Queries) GetTokensForUser(ctx context.Context, userID int64) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, getTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.Hash,
			&i.UserID,
			&i.Expiry,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
