// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"database/sql"
	"time"
)

type Account struct {
	ID                    int32
	AccountID             string
	ProviderID            sql.NullString
	UserID                int32
	AccessToken           sql.NullString
	RefreshToken          sql.NullString
	IDToken               sql.NullString
	AccessTokenExpiresAt  sql.NullTime
	RefreshTokenExpiresAt sql.NullTime
	Scope                 sql.NullString
	Password              string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type Author struct {
	ID   int32
	Name string
	Bio  sql.NullString
}

type Session struct {
	ID        int32
	ExpiresAt time.Time
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	IpAddress sql.NullString
	UserAgent sql.NullString
	UserID    int32
}

type User struct {
	ID            int32
	Name          string
	Email         string
	EmailVerified bool
	Image         sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
