// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    int32
	AccountID             string
	ProviderID            pgtype.Text
	UserID                int32
	AccessToken           pgtype.Text
	RefreshToken          pgtype.Text
	IDToken               pgtype.Text
	AccessTokenExpiresAt  pgtype.Timestamptz
	RefreshTokenExpiresAt pgtype.Timestamptz
	Scope                 pgtype.Text
	Password              pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type Author struct {
	ID   int32
	Name string
	Bio  pgtype.Text
}

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type Token struct {
	Hash   []byte
	UserID int64
	Expiry pgtype.Timestamptz
	Scope  string
}

type User struct {
	ID            int32
	Name          string
	Email         string
	EmailVerified bool
	Image         pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
